export const userActionTypes = {
    TOGGLE_SIGNINUP_HIDDEN: 'TOGGLE_SIGNINUP_HIDDEN',

    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOADED_SUCCESS: 'USER_LOADED_SUCCESS',
    USER_LOADED_FAIL: 'USER_LOADED_FAIL',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    USER_LOG_OUT: 'USER_LOG_OUT',
    
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    // 
    USER_DETAIL_REQUEST: 'USER_DETAIL_REQUEST',
    USER_DETAIL_SUCCESS: 'USER_DETAIL_SUCCESS',
    USER_DETAIL_FAIL: 'USER_DETAIL_FAIL',
    USER_DETAIL_RESET: 'USER_DETAIL_RESET',

    // Обновление пользовательских данных
    USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
    USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',

    // Активация аккаунта
    ACTIVATION_SUCCESS: 'ACTIVATION_SUCCESS',
    ACTIVATION_FAIL: 'ACTIVATION_FAIL',

    // сброс и востанавление пароля
    PASSWORD_RESET_SUCCES: 'PASSWORD_RESET_SUCCESS',
    PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAILS',
    PASSWORD_RESET_CONFIRM_SUCCES: 'PASSWORD__CONFIRM_SUCCESS',
    PASSWORD_RESET_CONFIRM_FAIL: 'PASSWORD_RESET_CONFIRM_FAIL',

}

