export const bagActionTypes = {
    TOGGLE_BAG_HIDDEN: 'TOGGLE_BAG_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM_FROM_BAG: 'REMOVE_ITEM_FROM_BAG',
    CLEAR_ITEM_FROM_BAG: 'CLEAR_ITEM_FROM_BAG',
    SAVE_SHIPPING_ADDRESS: 'SAVE_SHIPPING_ADDRESS',

    BAG_RESET: 'BAG_RESET',
}